### ISSUE TITLE
Byte 0 of mData (IsDeleted) is incorrectly initialised in the DbfRecord constructor

### ISSUE THREAD

**Issue by SlightlyMadGargoyle** [SocialExplorer/FastDBF#3]
mData is initialized in the DbfRecord constructor leaving mData[0] == 0. Valid values would be either '*' or ' ' as described in the setter of IsDeleted.

My quick fix is was to set IsDeleted to false after the initialization of mData.
```
        public DbfRecord(DbfHeader oHeader)
        {
            mHeader = oHeader;
            mHeader.Locked = true;

            //create a buffer to hold all record data. We will reuse this buffer to write all data to the file.
            mData = new byte[mHeader.RecordLength];
            IsDeleted = false; // Make sure mData[0] correctly represents 'not deleted'
            mEmptyRecord = mHeader.EmptyDataRecord;
            encoding = oHeader.encoding;

            for (int i = 0; i < oHeader.mFields.Count; i++)
                mColNameToConIdx[oHeader.mFields[i].Name] = i;
        }
```

**Comment by jotzaile** [comment]
I want to thank you so much for finding this bug. It has been driving me crazy for days.

The dbf File created with FastDBF was working ok everywhere but Access, when I tried to import with access it was showing "The Search Key was not found in any record".

If you google this error you can find regedit edits and so on but nothing helped me but this!

Thank you so so much.
