### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by escobar5** [SocialExplorer/FastDBF#4]
Hi,

I'm creating a DBF file with FastDBF, the file contains some data with accents (like áéíóúñ), I tried creating the db file with Encoding.UTF8, Encoding.Ansi, Encoding.Unicode, Encoding.Ascii, but those characters are not displaying ok when I open the DBF file.

Is there something else I should do to get this to work?

Thanks

**Comment by alacevic** [comment]
have you tried the 1252 codepage? it is not the default code page, a bit wider than the ascii set which is 7bit.

**Comment by escobar5** [comment]
Well, I don't know much of codepages, but I used 858 codepage and it worked fine. Thanks
